# Generated by Django 5.2.18 on 2026-10-08 15:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=220, verbose_name='título')),
                ('original_title', models.CharField(blank=True, max_length=220, verbose_name='título original')),
                ('synopsis', models.TextField(blank=True, verbose_name='sinopse')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='data de lançamento')),
                ('poster_url', models.URLField(blank=True, verbose_name='URL do pôster')),
                ('backdrop_url', models.URLField(blank=True, verbose_name='URL da imagem de fundo')),
                ('director', models.CharField(blank=True, max_length=220, verbose_name='direção')),
                ('cast', models.JSONField(blank=True, default=list, verbose_name='elenco')),
                ('genres', models.JSONField(blank=True, default=list, verbose_name='gêneros')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='país de produção')),
                ('tmdb_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='ID TMDB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('user', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField(blank=True, verbose_name='resenha')),
                ('is_spoiler', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_review_per_user_movie')],
            },
        ),
    ]
